### ISSUE TITLE
[1.19.2] A huge crash with the mod

### ISSUE THREAD

**Issue by u-ares** [TheComputerizer/Music-Triggers#138]
This one is a real doozy, but bare with me here; Something with this mod happened when I was modifying stuff for my modpack, which then happened to break the entire mod (even when I tried re-installing it completely)

I was making a system where a song would play every time you start a world (in this case, is it would be storming) but then I set the "play_once" value to 5. The modpack nearly crashed my computer (to the point where it would start beeping) but I was able to subvert it with task manager and a quick restart.
From then, I was unable to launch the modpack until I removed the mod and its configurations, since those seemed to be corrupted. I uninstalled the mod (and updated the Impossible Library for good measure) and it started working again.
Until I installed the mod again, which it was fine at first until I tried adding something using the in-game menu. It crashed and used up a ton of CPU once more like my previous crash, so I closed the game again like I did before.

I don't exactly know what I did, since I've been using a combination of modifying the direct example file and using the in-game menu for the entirety I've had this mod and experienced no problems. I don't think that the modpack doesn't tolerate this mod in specific anymore, since I've been carefully installing mods and doing quick tests to see if they're incompatible.

I've made this bug report to highlight a huge performance issue (I don't know if I can call it that) with the mod and to ask what I did to cause this big bug.
Thanks for reading and I hope you answer soon! Music is a really important aspect to my modpack and this has been a great tool to use for that!

Note 1: For context; I had 300 mods with shaders on (using Oculus), with some optimization mods such as Canary and Magnesium.
Note 2: I have a fairly decent computer with 24 GB of ram with 6080 GB allocated to Minecraft.

**Comment by TheComputerizer** [comment]
So play_once 3-5 haven't been implemented fully in 6.2 (6.3 has not been released yet which will have those). 

As for why you weren't able to launch, there is a good chance one of more of the config files corrupted rather than the mod itself (check and see if the file size for a config file seems unusually large which would explain why it might be taking a lot of resources to parse it or if there's an invalid table name with special characters for some reason)

Also if you updated The Impossible Library to 0.3.0, that versions isn't compatible with MT 6.2 but will be required once 6.3 comes out. Make sure you are using TIL 0.2.4 instead.

If you get any crashes make sure the include the crash report here

**Comment by u-ares** [comment]
Hey! I reinstalled again (this time clearing the configs and reverting TIL versions) and this time it works! I removed some stuff regarding the mod that were still in the modpack itself.
This is incredible work and I'm looking forward to version 6.3. Thanks again!
