### ISSUE TITLE
[1.12.2] opus codec support

### ISSUE THREAD

**Issue by ghost** [TheComputerizer/Music-Triggers#168]
I want to save disk space without compromising the quality of recordings by using the opus codec. But Music Triggers does not play music in opus format.

**Comment by TheComputerizer** [comment]
Opus encoding is supported assuming you are using one of the supported file formats which can be seen on the wiki [here](https://github.com/TheComputerizer/Music-Triggers/wiki/English#songs). But if you are really looking to save space you can always stream via the redirect as mentioned [here](https://github.com/TheComputerizer/Music-Triggers/wiki/English#redirect) instead of or in addition to having local files

**Comment by ghost** [comment]
Opus can be played if it is in a mkv container. This works, thanks.
