### ISSUE TITLE
[Forge 1.18.2-5.4-hf] NPE occurring occasionally

### ISSUE THREAD

**Issue by FyreAlchemage** [TheComputerizer/Music-Triggers#54]
**Describe the bug**
So far, the game has crashed twice; once while switching from the main menu to the world creation screen, and again when just unpausing the game after a moment. Both crashes mention NullPointerExceptions, caused by this mod.

**To Reproduce**
Steps to reproduce the behavior: Play the game normally, and occasionally it will crash. I don't yet know the exact causes.

**Additional context**
I am using the Bliss modpack, version 1.0.1; the included mod version is 5.4-hf. Both crash logs are attached.

[crash-2022-05-31_12.28.48-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/8807215/crash-2022-05-31_12.28.48-client.txt)
[crash-2022-05-31_11.57.18-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/8807217/crash-2022-05-31_11.57.18-client.txt)

**Comment by FreeFull** [comment]
Probably the same issue as #41

**Comment by TheComputerizer** [comment]
To give more information for those that are interested, the crash comes from [this line](https://github.com/TheComputerizer/Music-Triggers/blob/c36854e0675b9000ad5ecc0ba88440a84eb865c2/src/main/java/mods/thecomputerizer/musictriggers/client/MusicPlayer.java#L439) and happens because the music that tried to play failed to start playing for some reason, which means that the sound engine did not start tracking it and the source attached to a null sound instance is null.

**Comment by Linguardium** [comment]
I expect 6.0 is a big undertaking then; Should we expect a hotfix to fix this or is this a "remove until 6.0" situation?

**Comment by TheComputerizer** [comment]
It's something tied to the vanilla sound system itself, so it can't really be patched so easily with a hotfix. Most of the time the crash is a result of a config error with a mismatched song name though, it's just not very self explanatory. 6.0 should be out within the next few weeks anyways if everything goes well

**Comment by wertercatt** [comment]
https://mclo.gs/unlcGPH It is now happening on startup for me.

**Comment by TheComputerizer** [comment]
This is no longer an issue in 6.0
