### ISSUE TITLE
Make music added by pack developers loop seamlessly rather than stopping and starting again

### ISSUE THREAD

**Issue by Delfite** [TheComputerizer/Music-Triggers#73]
## **Describe your idea**
When music is added via any means and is set to loop continuously, the music that's currently active will briefly stop once it finishes and start back up from the beginning. This can be extremely jarring to listen to and severely breaks the player's immersion.

## **Describe alternatives you've considered**
I've attempted to use the ``min`` and ``max`` parameters to try and alleviate this problem but it just doesn't work the way I need it to.

## **Additional context**
Here's a video I made showcasing the lack of seamless looping:
https://user-images.githubusercontent.com/23504262/208579708-ad89e5eb-b87f-45cd-b3e0-ea25e8c3c949.mp4

I like this mod, but this issue pretty much kills it for me which is a shame due to how easy it is to work with. Hopefully this is fixed BEFORE 6.0's test build release date.

**Comment by TheComputerizer** [comment]
The loops should have been able to handle smooth transitions like that, but since it also used the vanilla sound system even that was a pretty big hack as it didn't have built in audio seeking.

Otherwise, I haven't fully tested it yet, but the custom sound engine I made for 6.0 has audio seeking built in a should be much smoother. The base function of the mod assumes different audio tracks, which is why it isn't going to inherently be smooth without some tweaking.

**Comment by TheComputerizer** [comment]
Closing this as 6.0 is released and this probably isn't an issue anymore. Feel free to open another issue if you still have problems
